### ISSUE TITLE
import - target species issue

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#190]
I was testing the import feature and noticed the target species column indicated it was going to make changes even though the target species column in the csv file was empty. It appears to want to add a space after the semicolon.
![image](https://github.com/MetaCell/scicrunch-antibody-registry/assets/50183178/4313d65a-6ef3-4154-9ff7-4d3cd925e2bb)
By confirming the import, this causes the target species values to be duplicated:
![image](https://github.com/MetaCell/scicrunch-antibody-registry/assets/50183178/4bd2e3e8-5999-418d-970f-50ce165c4b3c)
Also, updating does not seem to alter the Record History.

**Comment by afonsobspinto** [comment]
Hi @masonpairish.
I was trying to replicate the issue you reported but I'm struggling a bit to do so. I recorded a short video showcasing what I tried:

https://github.com/MetaCell/scicrunch-antibody-registry/assets/19196034/dbcb8e7e-93af-44e1-b248-5cf0fc8900ee

Could you let me know if those were the same steps you did?
If you have the change to do so, sharing the csv used in your scenario might be a useful insight for us to understand the problem.


In the process of checking this I also tested:
- If the order of the target species column in the csv mattered. It doesn't:

F.e. having 'human;rhesus;cynomolgu' in the csv would still report no changes:
![image](https://github.com/MetaCell/scicrunch-antibody-registry/assets/19196034/1a7bd5b1-939d-48fe-a9e7-59c72e59fa4b)

- If spaces in the target species column in the csv mattered. They don't:

F.e. having 'human; rhesus; cynomolgus ' in the csv would still report no changes:
![image](https://github.com/MetaCell/scicrunch-antibody-registry/assets/19196034/e06aa8a8-822b-4c68-aec6-3223c3fd72e5)

- If we can use comma (,) to separate species instead of semicolon (;). We can't. The split per species occurs on the semicolon if we were to have a comma in the csv it would be interpreted as 1 species only

**Comment by masonpairish** [comment]
The bug is still there. I've attached a csv.
[update entry.csv](https://github.com/MetaCell/scicrunch-antibody-registry/files/12402292/update.entry.csv)

**Comment by filippomc** [comment]
Thanks for providing the file. The issue is due to the semicolon being matched inconsistently in the original import, while colon is expected in the rest of the logic. Working on this
