### ISSUE TITLE
import preview gives wrong ab_id

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#196]
When importing a csv to get a SINGLE new entry the system reports the new id incorrectly.
Essentially the import picks the next ab_id but when the confirm button is pressed it skips that ab_id and goes to the next one.

PREDICTED:
![import ab_id predicted](https://github.com/MetaCell/scicrunch-antibody-registry/assets/50183178/777e967e-fd4b-42f5-a2b9-70d5588129c4)
ACTUAL:
![import ab_id actual](https://github.com/MetaCell/scicrunch-antibody-registry/assets/50183178/0a2959e0-4b48-43e1-9b0e-a9b55c959148)
When importing a csv to get a MULTIPLE new entries the system reports a list of new ab_ids but will skip all of those ab_ids to give a new list of ab_ids.

**Comment by filippomc** [comment]
Hi @masonpairish, the root cause of this is that the database isn't able to revert incremental keys after a transaction rollback, which is done upon the import simulation in the current implementation(see https://www.postgresql.org/message-id/20040419231615.656CFCF567C@www.postgresql.com)

Also it's not possible to accurately preview generated ids as during the import other users might upload antibodies, so the preview won't anyways be 100% accurate.

The best solution in my opinion is to remove the transactional save before the update and the related automatic generation of the antibody ids. This means that automatically generated fields (ix, ab_id, accession) won't be previewed. They'll be previewed in case they are part of the csv file content as it is now.
A good side effect is that by removing the save simulation the preview process will be faster.

**Comment by masonpairish** [comment]
I agree that the preview of the automatically generated fields is not necessary but they should be displayed AFTER the import has completed.
